### ISSUE TITLE
Move Any HBase Test Resources Out Of Main Resources

### ISSUE THREAD

**Issue by terrameta** [terrameta/cloudgraph#55]
Determine which if any resources in .hbase main resources are test resources and move accordingly. The challenge here is the hbase test are fairly extensive and require code generation and a complex data model. All this probably cannot happen as part of only maven test lifecycle. Probably requires creating a separate maven module e.g. cloudgraph-test which would encompass the test suites for all other modules where the tests require a full maven lifecycle.

**Comment by reddy6ue** [comment]
Or better yet, move to gradle and be free of the maven lifecycle altogether.
