### ISSUE TITLE
Cloud Graph config has properties that are better moved to a properties file

### ISSUE THREAD

**Issue by reddy6ue** [terrameta/cloudgraph#63]
Cloudgraph will be more intuitive, IMO, if the Property element in cloudgraph-config.xml is eliminated. Instead, it should be read from a cloudgraph.properties file outside the config xml file. If the properties file is injectable, it'll also increase flexibility by making cloudgraph configuration more accessible to injection frameworks like spring and guice. You could keep cloudgraph-config.xml as the default immutable xml file while reading properties from a configurable properties file (with the default being cloudgraph.properties).

**Comment by terrameta** [comment]
The existing 'config' is evolving more into a storage "profile" which can be changed and added to dynamically and parameterized with flat properties as recommended.
